


## Similar to summaryppc.R This function is designed to extract some of the useful summary information from the typical protein-protein-centric summary table generated by spectrum mill
# Applicable to TMT10 experiment complete summary reports reports
# The protein-protein-centric summary tables will be copied into a shared working directory (with unique names)
# The function directly scans the directory for the files, extracts the information and prepares a report
# Make sure there are not other files other than protein-protein-centric summary tables in the directory to be summarized

# Functional, last update on 06/23/2016

multi_summaryppc<-function(directory=NULL){ #ps is the name of the TMT10 protein centric summary table analyzed 
  
  ps<-dir()
  
  n<-length(ps)
  
  
  num_up <-NULL
  num_pro <-NULL
  num_pro_fq <-NULL
  num_pro_UP2 <-NULL
  num_pro_UP2fq <-NULL
  dirn<-NULL
  
  for(i in 1:n) {  # Looping over the ppc files in the current directory
  
                  ppc1<-read.csv2(ps[i],header=TRUE) #read the entire summary table
                  
                  w<-which(ppc1$species!="HUMAN") #Looking for non-human contaminants
                  
                  ppc1<-ppc1[-w,] #Removes non-human contaminants
                  
                  
                  dd<-as.character(colnames(ppc1)[2]) #
                  g <- regexpr("\\.[^\\.]*$", dd) # find the position of last dot
                  d<-substr(dd,1,g-1) #Name of the general data directory
                  
                  dirn<-c(dirn,d)
                  
                  UP<-which(colnames(ppc1)==paste(d,"unique_peptides",sep=".")) #Position of the unique peptide column
                  In1<-which(colnames(ppc1)==paste(d,"TMT_126_total",sep=".")) #The first intensity column
                  InL<-which(colnames(ppc1)==paste(d,"TMT_131_total",sep=".")) #The last intensity column
                  
                  
                  num_up_temp<-sum(ppc1[,UP]) # total number of unique peptides identified
                  num_up<-c(num_up,num_up_temp)
                  
                  
                  num_pro_temp<-length(ppc1[,"subgroupNum"]) #total number of unique proteins
                  num_pro<-c(num_pro,num_pro_temp)
                  
                  
                  
                  fqppc1<-ppc1[,In1:InL] # only intensity columns of ppc1UP2
                  m<-which(apply(is.na(fqppc1),1,sum)>0) #Finding the rows that contain at least one missing data (NA)
                  num_pro_fq_temp<-num_pro_temp-length(m) #total number of proteins fully quantified by all 10 TMT channelS
                  num_pro_fq<-c(num_pro_fq,num_pro_fq_temp)
                  
                  
                  w<-which(ppc1[,UP]>1) #Rows of proteins with at least 2 unique peptides
                  ppc1UP2<-ppc1[w,] # summary of proteins in ppc with at least 2 unique peptides
                  num_pro_UP2_temp<-length(ppc1UP2[,"subgroupNum"]) #total number of proteins with at least 2 unique peptides
                  num_pro_UP2<-c(num_pro_UP2,num_pro_UP2_temp)
                  
                  
                  fqppc1UP2<-ppc1UP2[,In1:InL] # only intensity columns of ppc1UP2
                  m<-which(apply(is.na(fqppc1UP2),1,sum)>0) #Finding the rows that contain at least one missing data (NA)
                  num_pro_UP2fq_temp<-num_pro_UP2_temp-length(m) #total number of proteins with at least 2 unique peptides and fully quantified by all 10 TMT channels
                  num_pro_UP2fq<-c(num_pro_UP2fq,num_pro_UP2fq_temp)
                  
          }    # Go to next ppc table in the directory until all the ppc files are finished
                  
                  
                  reportps<-data.frame(num_up,num_pro,num_pro_fq,num_pro_UP2,num_pro_UP2fq) #Construct a data table with the collected data
                  
                  colnames(reportps)<-c("number of unique peptides","number of unique proteins","number of fully quantified proteins","number of proteins with at least 2 unique peptides", "number of proteins with at least 2 unique peptides and fully quantified")
                  rownames(reportps)<-dirn
                    
                  finalreport<- t(reportps) # transposed version of the data table
                  
                  
                  
                  print(finalreport)
                  
                  write.csv(file=paste("multi_summaryppc.csv",sep="_"),finalreport) #printing the final report as a csv file
  
}